name: CI

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Build, Lint & Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.1"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Prisma Client
        run: cd apps/api && bunx prisma generate

      - name: Check code formatting
        run: bun run format:check

      - name: Lint code
        run: bun run lint:check

      - name: Type check
        run: bun run typecheck

      - name: Build all packages
        run: bun run build
